/**
 * End-to-end render test.
 *
 * audits/05-tests-qa.md flagged the absence of any test that actually
 * fires Playwright and produces a PDF. This file fills that gap.
 *
 * The test launches a real Chromium via the renderer service's browser
 * pool, calls renderPdf, and verifies that the resulting buffer is a
 * structurally valid PDF (correct magic header, EOF marker, sane page
 * count). It does NOT go through storage / DB / auth — those are
 * separately tested. The point is to catch regressions in the renderer
 * itself (browser pool race, sandbox argv, timeout wiring).
 *
 * Marked `slow` because launching Chromium takes ~600ms — kept off the
 * default vitest run to avoid blocking quick iteration. Run with
 * `vitest --run --testTimeout=60000` or via CI.
 */
import { describe, it, expect, afterAll } from 'vitest';
import { renderPdf, browserPool } from '../services/renderer.js';

const PDF_MAGIC = Buffer.from('%PDF-');
const PDF_EOF = Buffer.from('%%EOF');

const SAMPLE_HTML = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Deckle renderer-e2e test</title>
    <style>
      body { font-family: sans-serif; padding: 24px; }
      h1 { color: #F97316; }
    </style>
  </head>
  <body>
    <h1>Deckle renderer-e2e</h1>
    <p>If you can see this in a PDF viewer, the renderer works.</p>
    <p>Generated by the test suite at ${new Date().toISOString()}.</p>
  </body>
</html>`;

describe('renderer e2e (fires real Chromium)', () => {
  afterAll(async () => {
    // Tear the pool down so the test runner exits cleanly instead of
    // hanging on the long-lived browser processes.
    await browserPool.shutdown();
  });

  it(
    'renders simple HTML to a valid PDF buffer',
    async () => {
      const result = await renderPdf(SAMPLE_HTML, { format: 'A4' });

      expect(result.buffer.length).toBeGreaterThan(1000);
      expect(result.fileSize).toBe(result.buffer.length);

      // Structural: PDF must start with %PDF- and end with %%EOF.
      expect(result.buffer.subarray(0, 5).equals(PDF_MAGIC)).toBe(true);
      const tail = result.buffer.subarray(result.buffer.length - 32);
      expect(tail.includes(PDF_EOF)).toBe(true);

      // Page count: the page-count regex in renderer.ts should at
      // least produce something sensible for this single-page doc.
      expect(result.pages).toBeGreaterThanOrEqual(1);
      expect(result.pages).toBeLessThanOrEqual(2);
    },
    60_000,
  );

  it(
    'rejects HTML rendering when page.setContent times out',
    async () => {
      // A page that intentionally never resolves networkidle by
      // creating a long-lived <img> with no response. We don't host
      // such a server in CI, so simulate by including an image whose
      // src is unresolvable. networkidle won't fire; the timeout
      // (15s real, but we have to wait for it) kicks in.
      const stallingHtml = `<!DOCTYPE html><html><body>
        <img src="https://10.255.255.1/never-resolves.png" alt="">
      </body></html>`;

      await expect(renderPdf(stallingHtml)).rejects.toThrow(/timed out|setContent/i);
    },
    25_000,
  );

  it(
    'concurrent renders do not corrupt each other (pool race regression)',
    async () => {
      // Fire 5 renders in parallel. The pool's per-entry inFlight
      // counter (sprint 3-4 fix) must let all 5 finish with valid
      // PDFs. Before the fix this could return a closed-browser
      // entry and one of the calls would throw.
      const html = (i: number) =>
        `<!DOCTYPE html><html><body><h1>Doc ${i}</h1></body></html>`;
      const results = await Promise.all([0, 1, 2, 3, 4].map((i) => renderPdf(html(i))));
      for (const r of results) {
        expect(r.buffer.subarray(0, 5).equals(PDF_MAGIC)).toBe(true);
        expect(r.buffer.length).toBeGreaterThan(500);
      }
    },
    60_000,
  );
});
